'use client';
import { useState } from 'react';
import { Bell, ChevronDown, ClipboardList, Construction, FileText, LayoutDashboard, Package, Plus, Search, Settings, ShoppingBag, Users, MoreHorizontal, ArrowUpRight, Clock3, CircleCheck, Sun, Moon, Menu, X } from 'lucide-react';

const projects = [
 {name:'Riverside Apartments', client:'Balkan Properties', progress:72, status:'On track', color:'#5c72e5', due:'Oct 28', budget:'€248,000'},
 {name:'Central Business Hub', client:'Nova Developments', progress:41, status:'At risk', color:'#d89536', due:'Nov 12', budget:'€416,500'},
 {name:'Greenfield Residences', client:'Private client', progress:18, status:'On track', color:'#4ca982', due:'Jan 06', budget:'€189,200'},
];
const tasks = [{text:'Review concrete delivery schedule',project:'Riverside Apartments',time:'Today',done:false},{text:'Approve revised floor plans',project:'Central Business Hub',time:'Today',done:false},{text:'Order insulation materials',project:'Greenfield Residences',time:'Tomorrow',done:true},{text:'Submit weekly site report',project:'Riverside Apartments',time:'Oct 25',done:false}];
function NavItem({icon:Icon,label,active=false,badge}:{icon:any,label:string,active?:boolean,badge?:string}) { return <div className={'nav-item '+(active?'active':'')}><Icon size={18}/><span>{label}</span>{badge&&<b>{badge}</b>}</div> }
export default function Home(){ const [dark,setDark]=useState(false); const [mobile,setMobile]=useState(false); return <div className={dark?'app dark':'app'}>
 <aside className={mobile?'sidebar open':'sidebar'}><div className="brand"><div className="brand-mark"><Construction size={19}/></div><span>construct<strong>OS</strong></span><button className="close" onClick={()=>setMobile(false)}><X size={20}/></button></div><div className="company"><div className="company-logo">A</div><div><strong>Ardent Build Co.</strong><small>Workspace</small></div><ChevronDown size={15}/></div><div className="nav-label">Workspace</div><nav><NavItem icon={LayoutDashboard} label="Overview" active/><NavItem icon={ClipboardList} label="Projects" badge="6"/><NavItem icon={Users} label="People"/><NavItem icon={Package} label="Inventory"/><NavItem icon={FileText} label="Documents"/></nav><div className="nav-label market-label">Connect</div><nav><NavItem icon={ShoppingBag} label="Marketplace"/><NavItem icon={Bell} label="Notifications" badge="3"/></nav><div className="side-bottom"><NavItem icon={Settings} label="Settings"/><div className="profile"><div className="avatar">DM</div><div><strong>David Markovic</strong><small>Owner</small></div><MoreHorizontal size={17}/></div></div></aside>
 <main className="main"><header><button className="menu" onClick={()=>setMobile(true)}><Menu size={21}/></button><div className="crumb">Workspace <span>/</span> <strong>Overview</strong></div><div className="header-actions"><div className="search"><Search size={17}/><input placeholder="Search anything..."/><kbd>⌘ K</kbd></div><button className="icon-btn" onClick={()=>setDark(!dark)}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button><button className="icon-btn notification"><Bell size={18}/><i/></button><div className="header-avatar">DM</div></div></header><div className="content"><div className="welcome"><div><p className="eyebrow">Monday, October 21, 2024</p><h1>Good morning, David <span>✦</span></h1><p className="subhead">Here&apos;s what&apos;s happening across your company today.</p></div><button className="primary"><Plus size={17}/> New project</button></div>
 <section className="stat-grid"><div className="stat-card"><div className="stat-top"><span>Active projects</span><div className="stat-icon blue"><ClipboardList size={18}/></div></div><strong>6</strong><p><span className="up">↗ 12.5%</span> <em>vs last month</em></p></div><div className="stat-card"><div className="stat-top"><span>Revenue this month</span><div className="stat-icon green">€</div></div><strong>€84,290</strong><p><span className="up">↗ 8.2%</span> <em>vs last month</em></p></div><div className="stat-card"><div className="stat-top"><span>Open tasks</span><div className="stat-icon orange"><Clock3 size={18}/></div></div><strong>24</strong><p><span className="down">↘ 4.6%</span> <em>vs last month</em></p></div><div className="stat-card"><div className="stat-top"><span>Low stock items</span><div className="stat-icon red"><Package size={18}/></div></div><strong>8</strong><p><span className="attention">Needs attention</span></p></div></section>
 <div className="dashboard-grid"><section className="panel projects"><div className="panel-head"><div><h2>Projects</h2><p>Your active projects at a glance</p></div><button className="text-btn">View all <ArrowUpRight size={15}/></button></div><div className="project-list">{projects.map(p=><div className="project" key={p.name}><div className="project-title"><div className="project-dot" style={{background:p.color}}/><div><strong>{p.name}</strong><small>{p.client}</small></div><span className={'status '+(p.status==='At risk'?'risk':'')}>{p.status}</span><button className="dots"><MoreHorizontal size={18}/></button></div><div className="project-meta"><span>Progress <b>{p.progress}%</b></span><span>Due <b>{p.due}</b></span><span>Budget <b>{p.budget}</b></span></div><div className="progress"><i style={{width:p.progress+'%',background:p.color}}/></div></div>)}</div></section>
 <section className="panel tasks"><div className="panel-head"><div><h2>My tasks</h2><p>4 tasks need your attention</p></div><button className="text-btn">View all <ArrowUpRight size={15}/></button></div><div className="task-list">{tasks.map(t=><div className="task" key={t.text}><div className={'check '+(t.done?'checked':'')}>{t.done&&<CircleCheck size={18}/>}</div><div><strong className={t.done?'strike':''}>{t.text}</strong><small>{t.project}</small></div><span className={t.time==='Today'?'today':''}>{t.time}</span></div>)}</div><button className="add-task"><Plus size={16}/> Add a task</button></section></div>
 <div className="bottom-grid"><section className="panel activity"><div className="panel-head"><div><h2>Recent activity</h2><p>Updates from your team</p></div><button className="text-btn">View all <ArrowUpRight size={15}/></button></div><div className="activity-row"><div className="avatar purple">SL</div><p><strong>Sara Lewis</strong> uploaded <b>Floor plan v3.pdf</b><small>Riverside Apartments · 12 min ago</small></p></div><div className="activity-row"><div className="avatar teal">NP</div><p><strong>Nikola Petrov</strong> completed <b>Site inspection</b><small>Central Business Hub · 48 min ago</small></p></div></section><section className="tip"><div className="tip-icon">✦</div><div><p className="eyebrow">ConstructOS insight</p><h3>Keep your projects moving</h3><p>Central Business Hub is trending behind schedule. Review its open tasks to stay on track.</p><button className="tip-link">Review project <ArrowUpRight size={15}/></button></div></section></div>
 </div></main></div> }
